import React from "react";
import { FileText, BrainCircuit, FileSpreadsheet, Mic, Code2, Edit3, ListChecks } from "lucide-react";

const ResumeGeneratedQuize: React.FC = () => {
    return (
        <div className="min-h-screen bg-black text-white py-20 px-6 lg:px-12">

            {/* Page Title */}
            <h1 className="text-4xl font-bold mb-10 text-center">
                Smart AI-Powered Quiz Generator
            </h1>

            {/* ===== QUIZ SOURCES ===== */}
            <div className="grid grid-cols-1 md:grid-cols-3 gap-8 mb-16">

                {/* AI Generated Quiz */}
                <div className="p-6 bg-slate-900/60 rounded-2xl shadow-xl border border-slate-800 hover:bg-slate-800/70 transition">
                    <div className="flex items-center gap-3 mb-4">
                        <BrainCircuit className="w-8 h-8 text-blue-400" />
                        <h2 className="text-2xl font-bold">AI Generated Quiz</h2>
                    </div>
                    <p className="text-gray-300">
                        Create intelligent quizzes using AI-generated questions tailored to your learning needs.
                    </p>
                </div>

                {/* Resume Based Quiz */}
                <div className="p-6 bg-slate-900/60 rounded-2xl shadow-xl border border-slate-800 hover:bg-slate-800/70 transition">
                    <div className="flex items-center gap-3 mb-4">
                        <FileSpreadsheet className="w-8 h-8 text-blue-400" />
                        <h2 className="text-2xl font-bold">Resume-Based Quiz</h2>
                    </div>
                    <p className="text-gray-300">
                        Upload your resume and get customized quizzes based on your skills & experiences.
                    </p>
                </div>

                {/* PDF Based Quiz */}
                <div className="p-6 bg-slate-900/60 rounded-2xl shadow-xl border border-slate-800 hover:bg-slate-800/70 transition">
                    <div className="flex items-center gap-3 mb-4">
                        <FileText className="w-8 h-8 text-blue-400" />
                        <h2 className="text-2xl font-bold">PDF-Based Quiz</h2>
                    </div>
                    <p className="text-gray-300">
                        Generate quizzes instantly from uploaded PDF documents. Perfect for study notes.
                    </p>
                </div>

            </div>

            {/* ===== QUIZ TYPES ===== */}
            <h2 className="text-3xl font-bold mb-8 text-center">Quiz Types</h2>

            <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-8">

                {/* MCQ Quiz */}
                <QuizTypeCard
                    icon={<ListChecks className="w-10 h-10 text-purple-400" />}
                    title="MCQ Quiz"
                    desc="Multiple choice questions auto-generated by AI."
                />

                {/* Coding Quiz */}
                <QuizTypeCard
                    icon={<Code2 className="w-10 h-10 text-green-400" />}
                    title="Coding Quiz"
                    desc="AI generates code problems based on your skills."
                />

                {/* Voice Based Quiz */}
                <QuizTypeCard
                    icon={<Mic className="w-10 h-10 text-red-400" />}
                    title="Voice-Based Quiz"
                    desc="Answer questions via voice — great for interviews."
                />

                {/* Writing Based Quiz */}
                <QuizTypeCard
                    icon={<Edit3 className="w-10 h-10 text-blue-300" />}
                    title="Writing Quiz"
                    desc="Subjective, long-form answers graded by AI."
                />

            </div>
        </div>
    );
};

export default ResumeGeneratedQuize;


/* ===== Reusable Quiz Card Component ===== */

const QuizTypeCard = ({
    icon,
    title,
    desc,
}: {
    icon: React.ReactNode;
    title: string;
    desc: string;
}) => {
    return (
        <div className="p-6 bg-slate-900/60 rounded-2xl shadow-xl border border-slate-800 hover:bg-slate-800/70 transition flex flex-col items-start gap-3">
            {icon}
            <h3 className="text-xl font-semibold">{title}</h3>
            <p className="text-gray-400">{desc}</p>

            <button
                className="
                    mt-4 px-4 py-2 rounded-lg 
                    bg-gradient-to-r from-blue-600 to-purple-600 
                    hover:from-blue-700 hover:to-purple-700 
                    font-medium transition shadow-lg
                "
            >
                Start Quiz
            </button>
        </div>
    );
};